excluded_categories:
  type: list
  default: ""
  description:
    en: "List of excluded category slugs"
order_by_activity:
  type: list
  default: ""
  description:
    en: "Parent categories where children are ordered by activity"
show_unread:
  type: list
  default: ""
  description:
    en: "Parent categories to show unread counts"