excluded_categories:
  type: list
  default: ""
  description:
    en: "List of excluded category slugs"
order_by_activity:
  type: list
  default: ""
  description:
    en: "Parent categories where children are ordered by activity"
show_new:
  type: list
  default: ""
  description:
    en: "Parent categories to show new topic counts"